### PR TITLE
Handle multiple languages

### PR DESCRIPTION
**Pull request by ouoertheo**
Add ability to change language models

### CODE REVIEW

**Comment by xNissX233** [comment]
How exactly do I use this feature?

**Comment by ouoertheo** [comment]
I'll update instructions, but there's a new GET and POST endpoint on /tts/language to get available languages and set language, which downloads the model and sets it as the current one.

**Comment by xNissX233** [comment]
> I'll update instructions, but there's a new GET and POST endpoint on /tts/language to get available languages and set language, which downloads the model and sets it as the current one.

Do you think it would be possible to have a language selector in SillyTavern to be able to change languages depending on character? (or change them manually at least)

**Comment by ouoertheo** [comment]
Yep. It's on the list of things to do.

**Pull request merged**
